import { StyleSheet } from 'react-native'
export default StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: 20 },
  headerBox: {
    backgroundColor: '#96D289',
    paddingVertical: 10,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#122021',
  },
  card: {
    padding: 70,
    borderRadius: 20,
    marginBottom: 20,
    alignItems: 'center',
    elevation: 4,
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  baralhoInfo: {
    flex: 1,
    alignItems: 'center',
  },
  baralhoSubtext: {
    fontSize: 14,
    marginTop: 5,
    opacity: 0.8,
  },
  cardText: {
    fontSize: 18,
    fontWeight: 'normal',
  },
  optionButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deleteButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#fff',
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deleteButtonText: {
    fontSize: 16,
  },
  icon: {
    width: 60,
    height: 60,
  },
  icon2: {
    width: 50,
    height: 50,
  },
  fab: {
    position: 'absolute',
    bottom: 80,
    right: 30,
    backgroundColor: '#96D289',
    width: 50,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  fabText: {
    fontSize: 28,
    color: '#122021',
  },
  reviewButton: {
  backgroundColor: '#AD94DB',
  paddingVertical: 10,
  paddingHorizontal: 20,
  borderRadius: 12,
  alignSelf: 'center',
  marginTop: 15,
  marginBottom: 10,
},
reviewButtonText: {
  color: 'white',
  fontSize: 18,
  fontWeight: 'normal',
},
});